# Generated by Django 6.0 on 2025-12-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status do Pedido')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total Estimado')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço/Projeto')),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='PLANEJADO', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Unidade de Medida')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Material')),
                ('quantidade_estoque', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria', verbose_name='Categoria')),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.unidademedida', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA_MANUAL', 'Saída Manual'), ('CONSUMO', 'Consumo por Serviço')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência (Pedido/Ajuste)')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.material', verbose_name='Material Movimentado')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
            },
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_consumida', models.IntegerField(verbose_name='Quantidade Consumida')),
                ('data_consumo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Consumo')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.material', verbose_name='Material Consumido')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Registro de Consumo',
                'verbose_name_plural': 'Registros de Consumo',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.IntegerField(verbose_name='Quantidade Pedida')),
                ('preco_estimado_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário Estimado')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material Solicitado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pedidocompra', verbose_name='Pedido de Compra')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'unique_together': {('pedido', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ItemServicoNecessario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.IntegerField(verbose_name='Quantidade Necessária')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material', verbose_name='Material Necessário')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Item Necessário',
                'verbose_name_plural': 'Itens Necessários',
                'unique_together': {('servico', 'material')},
            },
        ),
    ]
