# Generated by Django 6.0 on 2025-12-14 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('contato', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade_pedida',
            field=models.PositiveIntegerField(verbose_name='Quantidade Pedida'),
        ),
        migrations.AlterField(
            model_name='itemserviconecessario',
            name='quantidade_necessaria',
            field=models.PositiveIntegerField(verbose_name='Quantidade Necessária'),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantidade_estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='Estoque Atual'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='registroconsumo',
            name='quantidade_consumida',
            field=models.PositiveIntegerField(verbose_name='Quantidade Consumida'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
