# Generated by Django 6.0 on 2025-12-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fornecedor_alter_itempedido_quantidade_pedida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2023-01-01 10:00', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
    ]
